<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('videos', function (Blueprint $table) {
            // Paths to low-res analysis assets generated by PrepareAnalysisAssetsJob.
            // Nulled out after GenerateThumbnailsJob cleans them up on success.
            $table->string('analysis_video_path')->nullable()->after('temp_path');
            $table->string('analysis_audio_path')->nullable()->after('analysis_video_path');

            // Highlight timestamps detected by Python (DetectHighlightsJob).
            // Consumed by CutClipsJob, not needed after that stage.
            $table->json('detected_highlights')->nullable()->after('analysis_audio_path');
        });
    }

    public function down(): void
    {
        Schema::table('videos', function (Blueprint $table) {
            $table->dropColumn(['analysis_video_path', 'analysis_audio_path', 'detected_highlights']);
        });
    }
};
